services:
  order:
    build: order-server/.
    ports:
      - "8080:8080"
    depends_on:
      - payment

    environment:
      - SPRING_PROFILES_ACTIVE=docker

  payment:
    build: payment-server/.
    ports:
      - "9090:9090"